apiVersion: v1
kind: Service
metadata:
  name: webapiservice
  #namespace: simplek8s-env-vars
  labels:
    app: weather-forecast
    service: webapi
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort : 80
      protocol: TCP
      nodePort: 30001
  selector:
    service: webapi